import A from "../assets/BISINDO/A/BISINDO.png";
import B from "../assets/BISINDO/B/BISINDO.png";
import C from "../assets/BISINDO/C/BISINDO.png";
import D from "../assets/BISINDO/D/BISINDO.png";
import E from "../assets/BISINDO/E/BISINDO.png";
import F from "../assets/BISINDO/F/BISINDO.png";
import G from "../assets/BISINDO/G/BISINDO.png";
import H from "../assets/BISINDO/H/BISINDO.png";
import I from "../assets/BISINDO/I/BISINDO.png";
import J from "../assets/BISINDO/J/BISINDO.png";
import K from "../assets/BISINDO/K/BISINDO.png";
import L from "../assets/BISINDO/L/BISINDO.png";
import M from "../assets/BISINDO/M/BISINDO.png";
import N from "../assets/BISINDO/N/BISINDO.png";
import O from "../assets/BISINDO/O/BISINDO.png";
import P from "../assets/BISINDO/P/BISINDO.png";
import Q from "../assets/BISINDO/Q/BISINDO.png";
import R from "../assets/BISINDO/R/BISINDO.png";
import S from "../assets/BISINDO/S/BISINDO.png";
import T from "../assets/BISINDO/T/BISINDO.png";
import U from "../assets/BISINDO/U/BISINDO.png";
import V from "../assets/BISINDO/V/BISINDO.png";
import W from "../assets/BISINDO/W/BISINDO.png";
import X from "../assets/BISINDO/X/BISINDO.png";
import Y from "../assets/BISINDO/Y/BISINDO.png";
import Z from "../assets/BISINDO/Z/BISINDO.png";

export default { A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z };
