import A from "../assets/SIBI/A/SIBI.png";
import B from "../assets/SIBI/B/SIBI.png";
import C from "../assets/SIBI/C/SIBI.png";
import D from "../assets/SIBI/D/SIBI.png";
import E from "../assets/SIBI/E/SIBI.png";
import F from "../assets/SIBI/F/SIBI.png";
import G from "../assets/SIBI/G/SIBI.png";
import H from "../assets/SIBI/H/SIBI.png";
import I from "../assets/SIBI/I/SIBI.png";
import J from "../assets/SIBI/J/SIBI.png";
import K from "../assets/SIBI/K/SIBI.png";
import L from "../assets/SIBI/L/SIBI.png";
import M from "../assets/SIBI/M/SIBI.png";
import N from "../assets/SIBI/N/SIBI.png";
import O from "../assets/SIBI/O/SIBI.png";
import P from "../assets/SIBI/P/SIBI.png";
import Q from "../assets/SIBI/Q/SIBI.png";
import R from "../assets/SIBI/R/SIBI.png";
import S from "../assets/SIBI/S/SIBI.png";
import T from "../assets/SIBI/T/SIBI.png";
import U from "../assets/SIBI/U/SIBI.png";
import V from "../assets/SIBI/V/SIBI.png";
import W from "../assets/SIBI/W/SIBI.png";
import X from "../assets/SIBI/X/SIBI.png";
import Y from "../assets/SIBI/Y/SIBI.png";
import Z from "../assets/SIBI/Z/SIBI.png";

export default { A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z };
